---
- name: Test to see if nodes already joined to cluster
  ansible.builtin.shell: ls /etc/kubernetes
  register: kubedirtest
  tags: kubedirtest

- name: Generate join token
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups.k8s_master[0] }}"

- ansible.builtin.set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Store join command
  action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"

- name: Run kubeadm join
  ansible.builtin.shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"
  when: "'pki' not in kubedirtest.stdout"
  tags: kubedirtest